### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time

### ISSUE THREAD

**Issue by eminisrafil** [dankogai/swift-sion#4] opened 2021-02-12 22:20 UTC
Anybody else getting this error when they compile?

`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

![image](https://user-images.githubusercontent.com/2307855/107828264-59165300-6d3d-11eb-93ff-3d402b888558.png)

Building to iOS 14 on Xcode 12.4 MacOS 11.2.1

**Comment by dankogai** [comment] 2021-02-13 02:42
I could not reproduce this error on:

* iMac (Retina 5K, 27-inch, Late 2014)
* MacBook Air (M1, 2020)

But the errors/warnings above is rather common (hence the `let` statements under `case`s to address past cases).  So I'll further break up expressions to make `swiftc` happier.

**Comment by dankogai** [comment] 2021-02-13 03:19
https://github.com/dankogai/swift-sion/commit/f6695f53d7832c48454487d882bba1781f5fe160 should fix your problem.  I am closing this issue but should the problem persist, please reopen.

**Closed as completed by dankogai** 2021-02-13 03:19 UTC
